"""initial schema

Revision ID: b92810e2904f
Revises: 
Create Date: 2026-07-01 13:52:14.507554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92810e2904f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopkeeper_profiles',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel_preference', sa.Enum('whatsapp', 'ussd', 'sms', name='channelenum'), nullable=False),
    sa.Column('locale', sa.Enum('kinyarwanda', 'english', name='localeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('forecast_results',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shopkeeper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('predicted_quantity', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('data_density_pct', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['shopkeeper_profiles.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('nlp_parse_results',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shopkeeper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('raw_message', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['shopkeeper_profiles.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('sales_logs',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shopkeeper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'ussd', 'sms', name='channelenum'), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['shopkeeper_profiles.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ussd_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('shopkeeper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shopkeeper_id'], ['shopkeeper_profiles.uuid'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ussd_sessions')
    op.drop_table('sales_logs')
    op.drop_table('nlp_parse_results')
    op.drop_table('forecast_results')
    op.drop_table('shopkeeper_profiles')
    # ### end Alembic commands ###
